apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubeshelf.fullname" . }}
  labels:
    {{- include "kubeshelf.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "kubeshelf.selector" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
